### ISSUE TITLE
Update access to various properties

### ISSUE THREAD

**Issue by pwalsh** [okfn/spend-publishing-dashboard#20]
The structure of the files that make up the database have gone through a change that is not reflected in the dashboard's data model.

If we use the Cabinet Office board as an example: http://cabinetoffice.dashboards.okfnlabs.org/#/

The following need to be updated:
- In the Overview section, the sources count is incorrect
- In the charts section, no attempt has been made to actually display result data for current or historical. this is captured in issue #11, but mentioned here for convenience
- In the Publishers table, `score` is not displayed as score is now available via a different file: the results.csv file can be used to sum the publisher's data for an overall score
- Likewise, on the list of sources, score needs to be calculated out of the results.csv file.

**Comment by hdurand** [comment]
The incorrect sources count comes from a CSV parsing error.
Pull request #22 fixes it.
