### ISSUE TITLE
Load all js files and libraries in bundle in gulpfile.js

### ISSUE THREAD

**Issue by hdurand** [okfn/spend-publishing-dashboard#25]
- They are currently loaded in `dashboard/dist/index.html`.
- Also, address this issue: this line https://github.com/okfn/spend-publishing-dashboard/blob/master/dashboard/dist/js/main.js#L15 applies to `.pricing-panels` elements but I didn't find any `.pricing-panels` element in the code so I let this line in `main.js`.

**Comment by pwalsh** [comment]
WONTFIX. There may be optimisations still, but the code has changed a lot since this point in time, so we'll reassess.
