### ISSUE TITLE
Jekyll-ifying

### ISSUE THREAD

**Issue by rufuspollock** [okfn/spend-publishing-dashboard#50]
```
_layouts/default.html
_layouts/publisher.html

index.html - home page
# publishers - use collections http://jekyllrb.com/docs/collections/
/publishers/xxx
```
### Basics
- [x] Move up dist stuff to base
- [x] Create layouts and refactor stuff out of react templates
- [ ] Move config stuff to _config.yml (out of JS and spd stuff)
- [ ] Refactor gulp to work off simple master - i.e. move styles etc down to base and js there - still have deploy to bundle js as needed ... (?)
### Publisher Pages
- [ ] List publishers with config in collections in _config.yml
- [ ] Publish layout
- [ ] Refactor JS to work on publisher pages
### Refactor
- [ ] Inline instance.json from external repo into local (maybe _config.yml)
  - [ ] connect JS app config and this ...
- [ ] Move data links into config (sort of already there)
### Optional:
- [ ] Submodule data - i.e. we submodule the csv in somewhere ... - so local and no need for cors etc

**Comment by pwalsh** [comment]
WONTFIX. We went to Node (and React).
