### ISSUE TITLE
Fix terminology in presentation of data

### ISSUE THREAD

**Issue by pwalsh** [okfn/spend-publishing-dashboard#59]
From @davidread

"Score" and "Correct" are confusing as they are conceptually similar.

Likewise, "Score (all time)" and "Score" creates further confusion.

Emphasis should be on having **all** the months formatted correctly, rather than just prioritising latest month ( point related to https://github.com/okfn/data-quality-cli/issues/5 ).

Suggested change:

Correct, Score (all time), Last file, Score -> Validity, Score, Last file

**Comment by Stephen-Gates** [comment]
Agreed @pwalsh. I'm thinking a binary score for Correct and Timely.
I'm no UI expert but perhaps a scorecard that shows progress over time.

<img width="288" alt="screenshot 2016-03-15 19 33 54" src="https://cloud.githubusercontent.com/assets/9379524/13773548/7db8b034-eae5-11e5-918f-0853341c5196.png">

Red = Not Correct and Not Timely
Orange = Not Correct or Not Timely
Green = Correct and Timely

Perhaps you could have no colour if the dataset was not published for that month.

**Comment by pwalsh** [comment]
Fixed.
