### ISSUE TITLE
Maintain lists of publishers and data sources

### ISSUE THREAD

**Issue by pwalsh** [okfn/spend-publishing-dashboard#6]
# User story 2A
- [x] Have a list of all publisher information
- [x] Have ability to update this list over time 
# User story 2B
- [x] List of publisher information
  - optional: group related publishers
- [x] Have a list of all data sources per publisher
  - [x] have a page that this list is accessible 
  - can also just be X most recent files
- [x] Store all these lists as CSV
- [x] Have them under version control (e.g.: github repo)

**Comment by pwalsh** [comment]
ref. [UI Mocks](https://drive.google.com/drive/#folders/0B4JzAmQXH28mTzJRZ1dqS25MZ1E/0B4JzAmQXH28mRVRxZWF0ci1uUlU/0B4JzAmQXH28mWVIyZy0yMGJ1VEU/0B4JzAmQXH28mQS0wSXFhUXA2YVk/0B6R8dXc6Ji4JUllnTzRxVEdfTFE/0B6R8dXc6Ji4Jc3M3RUs5bzZfa1E/0B4JzAmQXH28mfklzUVJvTEQwWXpyTFdKaWFhWFRBYUNEdFVLaWpGSUNqWHlEdXNaNzFjVlk)

Please comment there (or here) with feature ideas, or notes about user stories that are not served by the mocks.

**Comment by pwalsh** [comment]
@rgrp @tryggvib the problem with using GitHub here is CORS.

For the current sprint, I'll use http://rawgit.com which allows us to use GitHub and get around the CORS issue. 

For future, we can assess if this is good enough, or if we need to do an additional step of pushing sources to object store to serve without Cross Origin restrictions.

**Comment by rufuspollock** [comment]
@pwalsh i'm not sure i understand the CORS issue here.

**Comment by pwalsh** [comment]
If we have a GitHub repo which contains the data, e.g.:

somerepo.github.io/publishers.csv

and another which hosts a dashboard app, .e.g:

spenddashboard.com

The Dashboard app can't make XHR requests for the CSV data, as GitHub CORS doesn't allow it.

Maybe I missed something? (haven't checked this, just based on what I think I know about CORS and GitHub).

**Comment by pwalsh** [comment]
Publisher List: http://data.gov.uk/api/3/action/organization_list

Publisher Detail: http://data.gov.uk/api/3/action/organization_show?id=department-for-business-innovation-and-skills

**Comment by pwalsh** [comment]
The example data repo has the data model for the dashboard, and describes the storage of this data as CSV in git. 

https://github.com/pwalsh/spd-example
