### ISSUE TITLE
Gulp task 'scripts' is failing

### ISSUE THREAD

**Issue by georgiana-b** [okfn/spend-publishing-dashboard#61]
I have reverted to 1ad2a0b7c326793eed10200c8d4fd96d0cd44740 where `gulp` command used to work but now it's failing so I assume it's a dependency issue. I only managed to get rid of it by upgrading to     `browserify 12.0.0` which breaks other functionality. Help/advice needed.

**Comment by pwalsh** [comment]
@georgiana-b I am on it.

**Comment by pwalsh** [comment]
cc @akariv
