### ISSUE TITLE
Styles not loading on deploy

### ISSUE THREAD

**Issue by georgiana-b** [okfn/spend-publishing-dashboard#63]
I just made a clean deploy [here](https://dashboard-clean-slate.herokuapp.com). I have also tried following [this SO answer on the topic](http://stackoverflow.com/questions/26851120/how-can-i-setup-webpack-to-minify-and-combine-scss-and-javascript-like-codekit) with the same result. Help needed.

**Comment by akariv** [comment]
Seems like the webpack config does not build the css files.

**Comment by pwalsh** [comment]
correct. I'm got it fixed locally already. Sorry for delays :)

**Comment by pwalsh** [comment]
fixed.
