### ISSUE TITLE
Add demo instance, screen shots, or demonstration video

### ISSUE THREAD

**Issue by jmealo** [okfn/spend-publishing-dashboard#84]
Are there efforts to do any of the following? It sounds like I would need to use the cli to create the output just to see what the data-quality-dashboard looks like. That's a pretty big lift.

Here are some ideas of possible tasks:
- [x] Link to demo instance in README.md
- [ ] Add Screenshots to README.md
- [ ] Add "GIF" Screen Shots to README.md
- [ ] Link to Demonstration Video in README.md

**Comment by georgiana-b** [comment]
@jmealo Thanks for pointing that out! I included a link to a demo instance in the README. Please take a look and let me know if it's noticeable.
Do you think it'll do?
