### ISSUE TITLE
demo offline

### ISSUE THREAD

**Issue by COLABORATI** [okfn/spend-publishing-dashboard#85]
demo site http://uk-25k.openspending.org/ is offline. 

Is this project dead?

This is something that I always find very strange and annoying - it speaks in multiple ways about project status in a very negative way. A demo site must be monitored and kept disaster-prepared like any other live site - this is true also for projects about and made with public money.

**Comment by pwalsh** [comment]
Hi.

There is a demo here: http://uk-25k.datadashboards.io
